sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sumon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sumon/react-test npm test

after_success:
  - docker build -t docksumon/multi-client ./client
  - docker build -t docksumon/multi-nginx ./nginx
  - docker build -t docksumon/multi-server ./server
  - docker build -t docksumon/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push docksumon/multi-client
  - docker push docksumon/multi-nginx
  - docker push docksumon/multi-server
  - docker push docksumon/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker-aws'
  env: 'Multidockeraws-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-297107986940'
  bucket_path: 'multi-docker-aws'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
